services:
  - type: web
    name: cms-check-backend
    env: node
    region: frankfurt
    plan: free
    buildCommand: npm install --production
    startCommand: node server.js
    healthCheckPath: /health
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: JWT_SECRET
        generateValue: true
      - key: CLIENT_URL
        value: https://jfsagro-glitch.github.io/CMS_chek

