name: Deploy to GitHub Pages (Disabled)

on:
  # Отключен - используем deploy-gh-pages.yml
  # push:
  #   branches: [ main ]
  # workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: client/package-lock.json

      - name: Install dependencies
        run: |
          cd client
          echo "Installing dependencies..."
          npm install --legacy-peer-deps
          echo "Dependencies installed successfully"

      - name: Build
        run: |
          cd client
          echo "Starting build process..."
          export CI=false
          export GENERATE_SOURCEMAP=false
          npm run build
          echo "Build completed successfully"
          
      - name: Copy 404.html
        run: |
          cd client
          cp build/index.html build/404.html
          echo "404.html copied successfully"
          
      - name: List build files
        run: |
          cd client
          echo "Build directory contents:"
          ls -la build/
          echo "Static directory contents:"
          ls -la build/static/

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: client/build

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
